server:
  port: 8002
spring:
  application:
    name: user.query
  datasource:
    url: jdbc:mysql://localhost:3306/social_media_user?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: user
      auto-offset-reset: earliest
kafka:
  topic:
    name: user-events